---
- name: Install Tomcat 9 on Application Node
  hosts: app_servers
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - default-jdk
        - wget
        - unzip

    - name: Create tomcat user
      user:
        name: tomcat
        shell: /bin/false
        state: present

    - name: Download Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
        dest: /tmp/tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Rename tomcat directory if not exists
      command: mv /opt/apache-tomcat-9.0.85 /opt/tomcat
      args:
        removes: /opt/apache-tomcat-9.0.85
      when: not (ansible_facts['files']['/opt/tomcat'] is defined)

    - name: Change ownership of Tomcat directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
      args:
        executable: /bin/bash
